const catalystWeaverRecipes = [
  {
    id: 'aetherium-ingot-standard',
    groupId: 'aetherium-ingot',
    groupTitle: 'Aetherium Ingot',
    groupHint: 'Grouped by output item',
    variantLabel: 'Standard',
    variantNote: 'Default progression route and the cheapest in materials.',
    input: ['Gold Ingot ×1'],
    catalysts: ['Steel Ingot ×1', 'Energized Iron Ingot ×1', 'Ender Pearl Dust ×4', 'Aetherium Shard ×4'],
    fluid: ['Lava — 8,000 mB'],
    output: ['Aetherium Ingot ×1'],
    byproduct: ['Stabilized Obsidian Dust 0–2 (5%)'],
    cost: ['12,000 DE'],
    speed: ['0.5x'],
  },
  {
    id: 'aetherium-ingot-alternative',
    groupId: 'aetherium-ingot',
    groupTitle: 'Aetherium Ingot',
    variantLabel: 'Alternative',
    variantNote: 'Much faster, but significantly more expensive in rare materials.',
    input: ['Netherite Ingot ×1'],
    catalysts: ['Aetherium Shard ×4'],
    fluid: ['Lava — 8,000 mB'],
    output: ['Aetherium Ingot ×1'],
    byproduct: ['—'],
    cost: ['512,000 DE'],
    speed: ['12.0x'],
  },
  {
    id: 'stabilized-obsidian-dust',
    groupId: 'stabilized-obsidian-dust',
    groupTitle: 'Stabilized Obsidian Dust',
    input: ['Crying Obsidian Dust ×4'],
    catalysts: ['Glowstone Dust ×2', 'Energized Iron Dust ×1'],
    fluid: ['Liquified Aetherium — 250 mB'],
    output: ['Stabilized Obsidian Dust ×2'],
    byproduct: ['Obsidian ×1 (0.1%)'],
    cost: ['5,400 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'bronze-ingot',
    groupId: 'bronze-ingot',
    groupTitle: 'Bronze Ingot',
    input: ['Gold Ingot ×1'],
    catalysts: ['Copper Dust ×4'],
    fluid: ['—'],
    output: ['Bronze Ingot ×1'],
    byproduct: ['—'],
    cost: ['6,400 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'hyper-processing-upgrade',
    groupId: 'hyper-processing-upgrade',
    groupTitle: 'Hyper Processing Upgrade',
    input: ['Speed Upgrade ×1'],
    catalysts: ['Energized Iron Dust ×2', 'Aetherium Shard ×1', 'Titanium Plate ×1'],
    fluid: ['—'],
    output: ['Hyper Processing Upgrade ×1'],
    byproduct: ['—'],
    cost: ['12,800 DE'],
    speed: ['0.25x'],
  },
  {
    id: 'compressed-blackstone-4',
    groupId: 'compressed-blackstone-4',
    groupTitle: 'Compressed Blackstone 4',
    input: ['Quadruple Compressed Cobblestone ×1'],
    catalysts: ['Compressed Coal Block 4 ×1'],
    fluid: ['—'],
    output: ['Compressed Blackstone 4 ×1'],
    byproduct: ['—'],
    cost: ['601,600 DE'],
    speed: ['0.5x'],
  },
  {
    id: 'refined-aetherium-shard',
    groupId: 'refined-aetherium-shard',
    groupTitle: 'Refined Aetherium Shard',
    input: ['Aetherium Shard ×1'],
    catalysts: ['Amethyst Shard ×1'],
    fluid: ['Dark Matter — 800 mB'],
    output: ['Refined Aetherium Shard ×1'],
    byproduct: ['—'],
    cost: ['6,400 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'diamond',
    groupId: 'diamond',
    groupTitle: 'Diamond',
    input: ['Diamond Dust ×2'],
    catalysts: ['Iron Ingot ×1'],
    fluid: ['Lava — 100 mB'],
    output: ['Diamond ×1'],
    byproduct: ['—'],
    cost: ['3,200 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'emerald',
    groupId: 'emerald',
    groupTitle: 'Emerald',
    input: ['Emerald Dust ×2'],
    catalysts: ['Iron Ingot ×1'],
    fluid: ['Lava — 100 mB'],
    output: ['Emerald ×1'],
    byproduct: ['—'],
    cost: ['3,200 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'quartz',
    groupId: 'quartz',
    groupTitle: 'Quartz',
    input: ['Quartz Dust ×2'],
    catalysts: ['Iron Ingot ×1'],
    fluid: ['Lava — 100 mB'],
    output: ['Quartz ×1'],
    byproduct: ['—'],
    cost: ['3,200 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'amethyst-shard',
    groupId: 'amethyst-shard',
    groupTitle: 'Amethyst Shard',
    input: ['Amethyst Dust ×2'],
    catalysts: ['Iron Ingot ×1'],
    fluid: ['Lava — 100 mB'],
    output: ['Amethyst Shard ×1'],
    byproduct: ['—'],
    cost: ['3,200 DE'],
    speed: ['1.0x'],
  },
  {
    id: 'void-essence',
    groupId: 'void-essence',
    groupTitle: 'Void Essence',
    input: ['Glass Bottle ×1'],
    catalysts: ['Crushed Endstone ×1'],
    fluid: ['Dark Matter — 100 mB'],
    output: ['Void Essence ×1'],
    byproduct: ['—'],
    cost: ['32,000 DE'],
    speed: ['0.5x'],
  },
];

export default catalystWeaverRecipes;
