const machineProfiles = {
  assembler: {
    category: 'Processing',
    description: 'Automatically crafts the item recorded in a Digitizer blueprint from materials stored in its 3×3 input grid.',
    input: 'Digitizer blueprint + recipe materials',
    output: 'Blueprint-defined crafted item',
    primaryResource: 'Dorios Energy',
    howItWorks: [
      'Insert a blueprint created by the Digitizer into the dedicated blueprint slot.',
      'Supply the recipe materials through the nine material slots.',
      'Connect Dorios Energy and collect the crafted item from the output slot.',
    ],
    io: [
      ['Materials', 'Configurable item input · 9 slots'],
      ['Blueprint', 'Dedicated secondary input'],
      ['Items', 'Configurable output · 1 slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Recipe source', 'Digitizer blueprint'],
      ['Crafting layout', '3×3 material grid'],
      ['Batching', 'Scales with the Speed upgrade'],
    ],
  },
  autofisher: {
    category: 'Automation',
    description: 'Generates fishing loot while a valid fishing net is installed and water is present next to the machine. Net parameters control the available loot and each fishing roll.',
    input: 'Fishing net + nearby water',
    output: 'Fishing loot',
    primaryResource: 'Dorios Energy',
    howItWorks: [
      'Place the Auto Fisher with water in one of the neighboring blocks.',
      'Insert a UtilityCraft fishing net into the dedicated slot.',
      'Supply Dorios Energy and extract fishing loot from the output inventory.',
    ],
    io: [
      ['Fishing net', 'Dedicated secondary input'],
      ['Items', 'Configurable output · 9 slots'],
      ['Environment', 'Water in the adjacent 3×3×3 area'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Water check', 'Any neighboring block in a 3×3×3 area'],
      ['Net effects', 'Tier, speed, chance, amount, rolls and luck'],
      ['Loot storage', '9 output slots'],
    ],
  },
  autosieve: {
    category: 'Processing',
    description: 'Sifts registered blocks through an installed mesh and rolls resource drops according to that mesh’s tier and multipliers.',
    input: 'Sieveable block + Mesh',
    output: 'Tier-based resource drops',
    primaryResource: 'Dorios Energy',
    energy: 'Varies by sieve recipe',
    howItWorks: [
      'Insert a block accepted by the sieve recipe registry.',
      'Install a UtilityCraft mesh in the dedicated mesh slot.',
      'Supply Dorios Energy and extract the rolled drops from the output inventory.',
    ],
    io: [
      ['Blocks', 'Configurable item input · 1 slot'],
      ['Mesh', 'Dedicated secondary input'],
      ['Items', 'Configurable output · 9 slots'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Mesh progression', 'String through Netherite · 8 tiers'],
      ['Drop selection', 'Mesh tier and recipe chance'],
      ['Loot storage', '9 output slots'],
    ],
  },
  block_breaker: {
    category: 'Automation',
    description: 'Automatically breaks the valid solid block in front of the machine. An optional pickaxe is used when calculating tool-sensitive block loot.',
    input: 'Target block + optional pickaxe',
    output: 'Block loot in the world',
    primaryResource: 'Dorios Energy',
    howItWorks: [
      'Point the machine’s front face at the block to break.',
      'Optionally insert a pickaxe for blocks whose loot requires a suitable tool.',
      'Supply Dorios Energy; successful drops spawn at the broken block.',
    ],
    io: [
      ['Target', 'Front face'],
      ['Pickaxe', 'Configurable secondary item input'],
      ['Drops', 'Spawned at the target block'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Working face', 'Front face'],
      ['Tool slot', 'Optional pickaxe'],
      ['Excluded targets', 'Air, liquids and unbreakable blocks'],
    ],
  },
  block_placer: {
    category: 'Automation',
    description: 'Automatically places a supplied block into the empty space directly in front of the machine.',
    input: 'Placeable block',
    output: 'Block placed in the world',
    primaryResource: 'Dorios Energy',
    howItWorks: [
      'Orient the front face toward the intended placement position.',
      'Load a placeable block into the machine’s input slot.',
      'Supply Dorios Energy; the machine places one block whenever the target is empty.',
    ],
    io: [
      ['Items', 'Configurable input · 1 slot'],
      ['Placement', 'Front face'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Working face', 'Front face'],
      ['Target requirement', 'Empty block space'],
      ['Operation', 'Automatic, one block per completed action'],
    ],
  },
  crusher: {
    category: 'Processing',
    description: 'Processes registered Crusher recipes, breaking blocks, ores and materials down into crushed resources, dusts or lower-density forms.',
    input: 'Registered crushable item',
    output: 'Crushed material or dust',
    primaryResource: 'Dorios Energy',
    energy: 'Varies by crusher recipe',
    howItWorks: [
      'Insert an item registered in the Crusher recipe catalog.',
      'Supply Dorios Energy while the machine completes the recipe cost.',
      'Extract the processed result from the output slot.',
    ],
    io: [
      ['Items', 'Configurable input · 1 slot'],
      ['Items', 'Configurable output · 1 slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Recipe source', 'Crusher registry'],
      ['Item flow', 'Single input → single output'],
      ['Recipe cost', 'May override the machine default'],
    ],
  },
  digitizer: {
    category: 'Utility',
    description: 'Reads a valid 3×3 crafting layout and records its result and materials onto Blueprint Paper for use by the Assembler.',
    input: 'Blueprint Paper + 3×3 recipe pattern',
    output: 'Encoded blueprint',
    primaryResource: 'Dorios Energy',
    howItWorks: [
      'Arrange the recipe pattern across the nine material slots.',
      'Insert Blueprint Paper into the dedicated blueprint slot.',
      'Supply Dorios Energy and collect the encoded blueprint from the output slot.',
    ],
    io: [
      ['Pattern', 'Configurable item input · 9 slots'],
      ['Blueprint Paper', 'Dedicated secondary input'],
      ['Blueprint', 'Configurable output · 1 slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Pattern layout', '3×3 crafting grid'],
      ['Recipe validation', 'Minecraft Crafter + registered custom recipes'],
      ['Paired machine', 'Assembler'],
    ],
  },
  electro_press: {
    category: 'Processing',
    description: 'Runs registered pressing recipes to form plates, reconstruct resource chunks and compress compatible materials.',
    input: 'Registered press material',
    output: 'Plate, block or compressed material',
    primaryResource: 'Dorios Energy',
    energy: 'Varies by presser recipe',
    howItWorks: [
      'Insert a material accepted by the Electro Press recipe catalog.',
      'Supply Dorios Energy while the press completes the registered recipe.',
      'Extract the pressed result from the output slot.',
    ],
    io: [
      ['Items', 'Configurable input · 1 slot'],
      ['Items', 'Configurable output · 1 slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Recipe source', 'Presser registry'],
      ['Item flow', 'Single input → single output'],
      ['Supported operations', 'Plating, reconstruction and compression'],
    ],
  },
  ehxibitor: {
    category: 'Utility',
    description: 'Holds one item in a dedicated display slot for presentation. It is a passive utility block and does not process recipes or consume energy.',
    input: 'One display item',
    output: 'Displayed item',
    primaryResource: 'Display item',
    howItWorks: [
      'Place the item to present in the dedicated display slot.',
      'Leave the item stored while the Exhibitor presents it.',
      'Remove the item manually when the display is no longer needed.',
    ],
    io: [
      ['Items', 'Configurable input · 1 display slot'],
      ['Retrieval', 'Manual'],
      ['Energy', 'Not required'],
    ],
    specifications: [
      ['Display slots', '1'],
      ['Processing', 'None'],
      ['Energy required', 'None'],
    ],
  },
  harvester: {
    category: 'Automation',
    description: 'Harvests mature crops in a front-facing square, resets ordinary crops and breaks the upper growth of supported tall plants.',
    input: 'Mature crops in the work area',
    output: 'Harvested crop drops',
    primaryResource: 'Dorios Energy',
    energy: '100 DE / harvested cell',
    howItWorks: [
      'Orient the machine’s front face toward the crop area.',
      'Supply Dorios Energy; mature supported crops are harvested automatically.',
      'Install Range upgrades to expand the area and use Range IV to collect drops internally.',
    ],
    io: [
      ['Work area', 'Front-facing square'],
      ['Items', 'World drops; configurable 15-slot output at Range IV'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Base area', '3×3'],
      ['Maximum area', '9×9 at Range III'],
      ['Collection mode', 'Range IV stores drops in 15 output slots'],
      ['Crop support', 'Vanilla, registered UtilityCraft and supported tall crops'],
    ],
  },
  incinerator: {
    category: 'Processing',
    description: 'Processes registered Incinerator recipes with Dorios Energy, smelting dusts, raw UtilityCraft materials and compatible compressed resources.',
    input: 'Registered smeltable item',
    output: 'Smelted material',
    primaryResource: 'Dorios Energy',
    energy: 'Varies by furnace recipe',
    howItWorks: [
      'Insert an item registered in the Incinerator recipe catalog.',
      'Supply Dorios Energy instead of furnace fuel.',
      'Extract the smelted result from the output slot.',
    ],
    io: [
      ['Items', 'Configurable input · 1 slot'],
      ['Items', 'Configurable output · 1 slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Recipe source', 'Incinerator furnace registry'],
      ['Item flow', 'Single input → single output'],
      ['Fuel item', 'Not required'],
    ],
  },
  induction_anvil: {
    category: 'Utility',
    description: 'Repairs a damaged durable item continuously by converting Dorios Energy directly into restored durability.',
    input: 'Damaged durable item',
    output: 'Repaired item in the same slot',
    primaryResource: 'Dorios Energy',
    energy: '10 DE / durability point',
    omitConfiguredEnergy: true,
    howItWorks: [
      'Insert a damaged item with a durability component.',
      'Supply Dorios Energy while the item remains in the repair slot.',
      'Remove the item after it reaches the desired durability.',
    ],
    io: [
      ['Items', 'Configurable input · 1 repair slot'],
      ['Items', 'Manual retrieval from the same slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Repair cost', '10 DE per durability point before upgrade modifiers'],
      ['Repair rate', 'Limited by the machine’s current transfer rate'],
      ['Eligible items', 'Items with supported durability data'],
    ],
  },
  infuser: {
    category: 'Processing',
    description: 'Combines a catalyst with a base item through registered Infuser recipes to create alloys, machine components and advanced materials.',
    input: 'Catalyst + base item',
    output: 'Infused material',
    primaryResource: 'Dorios Energy',
    energy: 'Varies by infuser recipe',
    howItWorks: [
      'Insert the base item into the primary input slot.',
      'Insert the matching catalyst into the secondary input slot.',
      'Supply Dorios Energy and extract the infused result from the output slot.',
    ],
    io: [
      ['Base item', 'Configurable primary input · 1 slot'],
      ['Catalyst', 'Configurable secondary input · 1 slot'],
      ['Items', 'Configurable output · 1 slot'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Recipe key', 'Catalyst + base item'],
      ['Material inputs', '2 dedicated slots'],
      ['Recipe source', 'Infuser registry'],
    ],
  },
  magmatic_chamber: {
    category: 'Processing',
    description: 'Melts registered solid materials into liquid. Its built-in recipes convert stone-like blocks and magma materials into lava.',
    input: 'Registered meltable item',
    output: 'Recipe-defined liquid',
    primaryResource: 'Dorios Energy',
    energy: 'Varies by melter recipe',
    howItWorks: [
      'Insert a solid item registered in the Melter recipe catalog.',
      'Supply Dorios Energy while the chamber melts the material.',
      'Extract the resulting liquid through a configured fluid output side.',
    ],
    io: [
      ['Items', 'Configurable input · 1 slot'],
      ['Liquid', 'Configurable output · 1 tank'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Recipe source', 'Melter registry'],
      ['Built-in liquid', 'Lava'],
      ['Built-in yield', '250–1,000 mB per item'],
    ],
  },
  seed_synthesizer: {
    category: 'Processing',
    description: 'Uses a registered seed and an accepted soil as reference inputs to generate that plant’s configured drops.',
    input: 'Registered seed + accepted soil',
    output: 'Plant-specific resource drops',
    primaryResource: 'Dorios Energy',
    energy: 'Recipe cost × soil modifier',
    howItWorks: [
      'Keep a registered seed in the primary input slot.',
      'Install an accepted soil in the dedicated soil slot.',
      'Supply Dorios Energy and extract generated plant drops from the output inventory.',
    ],
    io: [
      ['Seed', 'Configurable primary input · 1 slot'],
      ['Soil', 'Configurable secondary input · 1 slot'],
      ['Items', 'Configurable output · 9 slots'],
      ['Energy', 'Dorios Energy network'],
    ],
    specifications: [
      ['Accepted soils', 'Dirt, Grass, Yellow, Red, Blue and Black Soil'],
      ['Soil energy modifier', '2×, 1.5×, 1×, 0.75×, 0.5× or 0.25×'],
      ['Drop selection', 'Registered plant loot and chance'],
    ],
  },
  xp_condenser: {
    category: 'Storage',
    description: 'Stores raw player experience as a fixed XP fluid and returns it without losing the exact amount. It also supports configurable XP-fluid input and output.',
    input: 'Player XP or XP fluid',
    output: 'Player XP or XP fluid',
    primaryResource: 'Experience (XP)',
    howItWorks: [
      'Use the controls to deposit 1 level, 5 levels or the maximum available XP.',
      'Keep XP stored in the condenser or transfer it through configured fluid sides.',
      'Withdraw 1 level, 5 levels or all stored XP when needed.',
    ],
    io: [
      ['Player transfer', 'Deposit and withdraw controls'],
      ['XP fluid', 'Configurable input and output'],
      ['Energy', 'Not required'],
    ],
    specifications: [
      ['Fluid type', 'Fixed Experience (XP)'],
      ['Manual controls', 'Deposit/withdraw 1 level, 5 levels or max'],
      ['Accounting', 'Exact raw XP'],
      ['Energy required', 'None'],
    ],
  },
};

export default machineProfiles;
