const pageCopy = {
  en: {
    support: {
      title: 'Support Dorios', description: 'Join and support the Dorios Studios community.', kicker: 'Community & support',
      headingBefore: 'The best worlds are ', headingAccent: 'shared.',
      lead: 'Follow the work, meet other players, and help keep Dorios addons free for everyone who wants to play.',
      linksLabel: 'Community links', opensNewTab: 'opens in a new tab',
      links: {
        discord: ['Community', 'Join our Discord', 'Meet the community'],
        youtube: ['Updates', 'Watch on YouTube', 'Watch the latest'],
        github: ['Open work', 'Visit GitHub', 'Explore repositories'],
        patreon: ['Support Dorios', 'Become a Patron', 'Help keep addons free'],
      },
    },
    studio: {
      title: 'The Studio', description: 'The people, history and principles behind Dorios Studios.',
      kicker: 'Independent Bedrock studio · Est. 2022', headingBefore: 'Small team. ', headingAccent: 'Bigger worlds.',
      lead: 'Dorios Studios is a collective of creators building free Minecraft Bedrock add-ons around useful systems, deliberate progression and a community that keeps shaping the work.',
      meetStaff: 'Meet the staff', exploreProjects: 'Explore projects', factsLabel: 'Studio at a glance',
      facts: [['Founded', '09.09.2022'], ['Platform', 'Minecraft Bedrock'], ['Focus', 'Free, player-first add-ons']],
      missionKicker: 'Why we exist', missionTitle: 'Build more possibility into every world.',
      mission: ['We believe Bedrock players should have access to ambitious, high-quality experiences without putting the most interesting ideas behind a paywall.', 'Our work ranges from industrial automation to exploration and custom mechanics, but the standard stays the same: approachable at the start, rewarding as a system, and worth sharing.'],
      storyKicker: 'Our story', storyTitle: 'Built through iteration.', storyLead: 'From individual experiments to a multidisciplinary Bedrock collective.',
      timeline: [
        ['2020', 'The first experiments', 'Milo504 began creating Bedrock add-ons with More Armors, followed by Tools, Weapons and More—the project that would eventually grow into UtilityCraft.'],
        ['2022', 'Dorios Studios takes shape', 'Milo504 and WeatherVictor founded Dorios Studios on September 9, bringing development and interface design under one shared identity.'],
        ['2024', 'A clearer visual language', 'JR.ice joined as lead designer and texture artist. UtilityCraft 3.0 followed, giving the studio its first major milestone in the Bedrock community.'],
      ],
      approachKicker: 'Our approach', approachTitle: 'Principles that survive the prototype.', approachLead: 'Open a principle to see how it guides the work.',
      approaches: [
        ['01', 'Bedrock first', 'Design for the platform players actually use.', 'Controls, multiplayer, performance and the Bedrock add-on ecosystem shape each decision from the beginning—they are not an adaptation step at the end.'],
        ['02', 'Systems with purpose', 'Give every mechanic a place in progression.', 'Useful automation, readable progression and room for experimentation turn isolated features into worlds that remain interesting tomorrow.'],
        ['03', 'Community shaped', 'Treat feedback as part of the work.', 'Players and testers help reveal what is unclear, unbalanced or simply not fun yet. That feedback informs how add-ons are refined over time.'],
      ],
      directoryKicker: 'Inside the studio', directoryTitle: 'People and acknowledgements.', directoryLead: 'Staff records who makes the work. Credits records everyone and everything that helps it happen.',
      peopleLabel: '01 / People', staff: 'Staff', staffCopy: 'Meet the studio team, their primary disciplines and the collaborating creators around them.', viewStaff: 'View staff',
      creditsLabel: '02 / Acknowledgements', credits: 'Credits', creditsCopy: 'Contributors, testers, community support and the open-source tools behind the site.', readCredits: 'Read credits',
      communityKicker: 'Community & values', communityTitle: 'Feedback belongs in the process.', communityCopy: 'Share what works, report what does not, and help us understand what Bedrock players want to build next. Thoughtful community input makes every release stronger.',
      joinConversation: 'Join the conversation', supportStudio: 'Support the studio',
    },
    staff: {
      title: 'Staff · The Studio', description: 'Meet the staff and collaborating creators behind Dorios Studios.', overview: 'Overview', staff: 'Staff', credits: 'Credits',
      sectionsLabel: 'The Studio sections', profileLabel: 'View {name}\'s profile', portraitLabel: 'Portrait of {name}', owner: 'Owner', specialtiesLabel: '{name} specialties',
      kicker: 'People behind the work', headingBefore: 'Different disciplines. ', headingAccent: 'One studio.',
      lead: 'Development, interfaces, art, animation and community work come together here. Profiles are grouped by each person’s primary published role.',
      recordLabel: 'About this staff record', recordTitle: 'About this record', recordCopy: 'Roles follow the studio’s currently published team profiles. No personal links are shown unless the studio has provided one publicly.',
      directoryLabel: 'Dorios Studios team directory', developerKicker: 'Developer resources', developerTitle: 'Build with Dorios scripts.', developerCopy: 'Browse the scripting reference, examples and APIs used across the studio’s Bedrock projects.', openDocs: 'Open script documentation',
      nextKicker: 'Beyond the staff', nextTitle: 'Many more hands make the work possible.', nextCopy: 'Continue to contributors, testers, special thanks and the tools behind Dorios Studios.', exploreCredits: 'Explore the credits',
      groups: {
        leadership: ['Leadership', 'Direction, development and the foundation of the studio.'], development: ['Development', 'Code, quality review and systems implementation.'],
        'art-design': ['Art & Design', 'The visual language, movement and spaces that give projects character.'], community: ['Community', 'Independent creators who collaborate with the studio and its projects.'],
      },
    },
    credits: {
      title: 'Credits · The Studio', description: 'Contributors, testers, acknowledgements and tools behind Dorios Studios.', overview: 'Overview', staff: 'Staff', credits: 'Credits', sectionsLabel: 'The Studio sections',
      kicker: 'Acknowledgements', headingBefore: 'Credit where ', headingAccent: 'credit is due.', lead: 'Dorios Studios grows through project contributions, patient testing, community feedback and open tools. This record names only credits supported by the studio’s project files.',
      policyLabel: 'Credit policy', policyTitle: 'Credit policy', policyCopy: 'A missing name is left open instead of guessed. If a published credit needs to be added or corrected, contact the studio through Discord.', correction: 'Request a correction',
      contributorsEyebrow: 'Project work', contributorsTitle: 'Contributors', contributor: 'Named contributor · Ascendant Technology 0.8', creator: 'Creator · Better Smelters',
      translatorsEyebrow: 'Localization', translatorsTitle: 'Translators', noTranslators: 'No individual translators are currently published.', translatorsCopy: 'Verified localization credits will be listed here as they are provided by the studio.',
      testersEyebrow: 'Quality & feedback', testersTitle: 'Testers', testersCopy: 'These testers are explicitly acknowledged for helping refine Dorios Studios projects through feedback and play.', communityTester: 'Community tester',
      thanksEyebrow: 'Asset permission', thanksTitle: 'Special Thanks', thanksCopy: 'For granting permission to use the water and Cryofluid icon assets documented by Ascendant Technology.', originalWork: 'View the original work',
      communityEyebrow: 'The wider circle', communityTitle: 'Community Support', communityCopy: 'To every player who reports a bug, explains a confusing system, shares a build or stays through an early release: your feedback helps turn experiments into reliable add-ons.', joinCommunity: 'Join or support the community',
      toolsEyebrow: 'Website foundation', toolsTitle: 'Tools & Open Source', toolsCopy: 'Packages named here are declared directly by the Dorios website project.', visitTool: 'Visit {name}',
      nextKicker: 'The current team', nextTitle: 'Meet the people behind Dorios Studios.', nextCopy: 'See the published roles across leadership, development, art, design and community.', exploreStaff: 'Explore the staff',
      toolUses: ['Static site and documentation framework', 'Component rendering and interaction layer', 'Documentation content with component support', 'Readable syntax highlighting for technical content', 'Self-hosted Space Grotesk and League Spartan font packages', 'Local documentation search'],
    },
  },
  'pt-BR': {
    support: {
      title: 'Apoie a Dorios', description: 'Participe e apoie a comunidade da Dorios Studios.', kicker: 'Comunidade e apoio', headingBefore: 'Os melhores mundos são ', headingAccent: 'compartilhados.',
      lead: 'Acompanhe nosso trabalho, conheça outros jogadores e ajude a manter os addons da Dorios gratuitos para todos.', linksLabel: 'Links da comunidade', opensNewTab: 'abre em uma nova aba',
      links: {discord: ['Comunidade', 'Entre no nosso Discord', 'Conheça a comunidade'], youtube: ['Novidades', 'Assista no YouTube', 'Veja as novidades'], github: ['Código aberto', 'Visite o GitHub', 'Explore os repositórios'], patreon: ['Apoie a Dorios', 'Seja um apoiador', 'Ajude a manter os addons gratuitos']},
    },
    studio: {
      title: 'O Estúdio', description: 'As pessoas, a história e os princípios da Dorios Studios.', kicker: 'Estúdio Bedrock independente · Desde 2022', headingBefore: 'Equipe pequena. ', headingAccent: 'Mundos maiores.',
      lead: 'A Dorios Studios é um coletivo de criadores que desenvolve addons gratuitos para Minecraft Bedrock, com sistemas úteis, progressão bem pensada e uma comunidade que continua moldando o trabalho.',
      meetStaff: 'Conheça a equipe', exploreProjects: 'Explore os projetos', factsLabel: 'O estúdio em resumo', facts: [['Fundação', '09.09.2022'], ['Plataforma', 'Minecraft Bedrock'], ['Foco', 'Addons gratuitos feitos para jogadores']],
      missionKicker: 'Por que existimos', missionTitle: 'Criar mais possibilidades em cada mundo.', mission: ['Acreditamos que jogadores de Bedrock merecem experiências ambiciosas e de alta qualidade sem que as ideias mais interessantes fiquem atrás de uma cobrança.', 'Nosso trabalho vai da automação industrial à exploração e mecânicas personalizadas, sempre com o mesmo padrão: acessível no começo, recompensador como sistema e bom de compartilhar.'],
      storyKicker: 'Nossa história', storyTitle: 'Construída por iteração.', storyLead: 'De experimentos individuais a um coletivo multidisciplinar de Bedrock.',
      timeline: [['2020', 'Os primeiros experimentos', 'Milo504 começou a criar addons de Bedrock com More Armors, seguido por Tools, Weapons and More — o projeto que mais tarde se tornaria UtilityCraft.'], ['2022', 'A Dorios Studios ganha forma', 'Milo504 e WeatherVictor fundaram a Dorios Studios em 9 de setembro, reunindo desenvolvimento e design de interfaces sob uma identidade comum.'], ['2024', 'Uma linguagem visual mais clara', 'JR.ice entrou como designer principal e artista de texturas. UtilityCraft 3.0 veio em seguida, tornando-se o primeiro grande marco do estúdio na comunidade Bedrock.']],
      approachKicker: 'Nossa abordagem', approachTitle: 'Princípios que sobrevivem ao protótipo.', approachLead: 'Abra um princípio para ver como ele orienta o trabalho.',
      approaches: [['01', 'Bedrock primeiro', 'Projetar para a plataforma que os jogadores realmente usam.', 'Controles, multijogador, desempenho e o ecossistema de addons Bedrock orientam cada decisão desde o início; não são uma adaptação feita no final.'], ['02', 'Sistemas com propósito', 'Dar a cada mecânica um lugar na progressão.', 'Automação útil, progressão legível e espaço para experimentar transformam recursos isolados em mundos que continuam interessantes amanhã.'], ['03', 'Moldado pela comunidade', 'Tratar o feedback como parte do trabalho.', 'Jogadores e testadores ajudam a revelar o que está confuso, desequilibrado ou ainda não está divertido. Esse retorno orienta a evolução dos addons.']],
      directoryKicker: 'Dentro do estúdio', directoryTitle: 'Pessoas e agradecimentos.', directoryLead: 'A equipe registra quem faz o trabalho. Os créditos registram todas as pessoas e ferramentas que o tornam possível.', peopleLabel: '01 / Pessoas', staff: 'Equipe', staffCopy: 'Conheça a equipe do estúdio, suas principais áreas e os criadores que colaboram conosco.', viewStaff: 'Ver equipe', creditsLabel: '02 / Agradecimentos', credits: 'Créditos', creditsCopy: 'Colaboradores, testadores, apoio da comunidade e ferramentas de código aberto por trás do site.', readCredits: 'Ler créditos',
      communityKicker: 'Comunidade e valores', communityTitle: 'O feedback faz parte do processo.', communityCopy: 'Compartilhe o que funciona, relate o que não funciona e nos ajude a entender o que jogadores de Bedrock querem construir a seguir. Um retorno cuidadoso fortalece cada lançamento.', joinConversation: 'Participe da conversa', supportStudio: 'Apoie o estúdio',
    },
    staff: {
      title: 'Equipe · O Estúdio', description: 'Conheça a equipe e os criadores que colaboram com a Dorios Studios.', overview: 'Visão geral', staff: 'Equipe', credits: 'Créditos', sectionsLabel: 'Seções do Estúdio', profileLabel: 'Ver o perfil de {name}', portraitLabel: 'Retrato de {name}', owner: 'Fundador', specialtiesLabel: 'Especialidades de {name}',
      kicker: 'Pessoas por trás do trabalho', headingBefore: 'Disciplinas diferentes. ', headingAccent: 'Um só estúdio.', lead: 'Desenvolvimento, interfaces, arte, animação e comunidade se encontram aqui. Os perfis são agrupados pela principal função publicada de cada pessoa.', recordLabel: 'Sobre este registro da equipe', recordTitle: 'Sobre este registro', recordCopy: 'As funções seguem os perfis atualmente publicados pelo estúdio. Links pessoais só aparecem quando foram divulgados publicamente pela equipe.', directoryLabel: 'Diretório da equipe Dorios Studios',
      developerKicker: 'Recursos para desenvolvedores', developerTitle: 'Crie com os scripts da Dorios.', developerCopy: 'Consulte a referência de scripts, exemplos e APIs usadas nos projetos Bedrock do estúdio.', openDocs: 'Abrir documentação de scripts', nextKicker: 'Além da equipe', nextTitle: 'Muitas outras mãos tornam este trabalho possível.', nextCopy: 'Continue para colaboradores, testadores, agradecimentos especiais e as ferramentas por trás da Dorios Studios.', exploreCredits: 'Explorar os créditos',
      groups: {leadership: ['Liderança', 'Direção, desenvolvimento e a base do estúdio.'], development: ['Desenvolvimento', 'Código, revisão de qualidade e implementação de sistemas.'], 'art-design': ['Arte e Design', 'A linguagem visual, o movimento e os espaços que dão personalidade aos projetos.'], community: ['Comunidade', 'Criadores independentes que colaboram com o estúdio e seus projetos.']},
    },
    credits: {
      title: 'Créditos · O Estúdio', description: 'Colaboradores, testadores, agradecimentos e ferramentas por trás da Dorios Studios.', overview: 'Visão geral', staff: 'Equipe', credits: 'Créditos', sectionsLabel: 'Seções do Estúdio', kicker: 'Agradecimentos', headingBefore: 'Crédito a quem ', headingAccent: 'merece.', lead: 'A Dorios Studios cresce com contribuições aos projetos, testes cuidadosos, feedback da comunidade e ferramentas abertas. Este registro lista apenas créditos confirmados pelos arquivos dos projetos.', policyLabel: 'Política de créditos', policyTitle: 'Política de créditos', policyCopy: 'Um nome ausente fica em aberto em vez de ser presumido. Para adicionar ou corrigir um crédito publicado, entre em contato pelo Discord.', correction: 'Solicitar uma correção',
      contributorsEyebrow: 'Trabalho nos projetos', contributorsTitle: 'Colaboradores', contributor: 'Colaborador creditado · Ascendant Technology 0.8', creator: 'Criador · Better Smelters', translatorsEyebrow: 'Localização', translatorsTitle: 'Tradutores', noTranslators: 'Nenhum tradutor individual está publicado no momento.', translatorsCopy: 'Créditos de localização verificados serão listados aqui quando forem fornecidos pelo estúdio.', testersEyebrow: 'Qualidade e feedback', testersTitle: 'Testadores', testersCopy: 'Estes testadores são reconhecidos por ajudar a aprimorar os projetos da Dorios Studios com testes e feedback.', communityTester: 'Testador da comunidade', thanksEyebrow: 'Permissão de recursos', thanksTitle: 'Agradecimentos especiais', thanksCopy: 'Por conceder permissão para usar os ícones de água e Cryofluid documentados pela Ascendant Technology.', originalWork: 'Ver trabalho original', communityEyebrow: 'O círculo mais amplo', communityTitle: 'Apoio da comunidade', communityCopy: 'A cada jogador que relata um erro, explica um sistema confuso, compartilha uma construção ou acompanha uma versão inicial: seu feedback transforma experimentos em addons confiáveis.', joinCommunity: 'Participar ou apoiar a comunidade', toolsEyebrow: 'Base do site', toolsTitle: 'Ferramentas e código aberto', toolsCopy: 'Os pacotes listados aqui são declarados diretamente pelo projeto do site Dorios.', visitTool: 'Visitar {name}', nextKicker: 'A equipe atual', nextTitle: 'Conheça as pessoas por trás da Dorios Studios.', nextCopy: 'Veja as funções publicadas em liderança, desenvolvimento, arte, design e comunidade.', exploreStaff: 'Explorar a equipe',
      toolUses: ['Framework de site estático e documentação', 'Camada de renderização e interação de componentes', 'Conteúdo de documentação com suporte a componentes', 'Destaque de sintaxe legível para conteúdo técnico', 'Pacotes locais das fontes Space Grotesk e League Spartan', 'Busca local na documentação'],
    },
  },
  'es-MX': {
    support: {
      title: 'Apoya a Dorios', description: 'Únete y apoya a la comunidad de Dorios Studios.', kicker: 'Comunidad y apoyo', headingBefore: 'Los mejores mundos se ', headingAccent: 'comparten.', lead: 'Sigue nuestro trabajo, conoce a otros jugadores y ayuda a mantener gratuitos los addons de Dorios para todos.', linksLabel: 'Enlaces de la comunidad', opensNewTab: 'abre en una pestaña nueva', links: {discord: ['Comunidad', 'Únete a nuestro Discord', 'Conoce a la comunidad'], youtube: ['Novedades', 'Míranos en YouTube', 'Mira lo más reciente'], github: ['Trabajo abierto', 'Visita GitHub', 'Explora los repositorios'], patreon: ['Apoya a Dorios', 'Hazte patrocinador', 'Ayuda a mantener gratuitos los addons']},
    },
    studio: {
      title: 'El Estudio', description: 'Las personas, la historia y los principios de Dorios Studios.', kicker: 'Estudio Bedrock independiente · Desde 2022', headingBefore: 'Equipo pequeño. ', headingAccent: 'Mundos más grandes.', lead: 'Dorios Studios es un colectivo de creadores que desarrolla addons gratuitos para Minecraft Bedrock con sistemas útiles, progreso deliberado y una comunidad que sigue dando forma al trabajo.', meetStaff: 'Conoce al equipo', exploreProjects: 'Explora los proyectos', factsLabel: 'El estudio de un vistazo', facts: [['Fundación', '09.09.2022'], ['Plataforma', 'Minecraft Bedrock'], ['Enfoque', 'Addons gratuitos pensados para jugadores']],
      missionKicker: 'Por qué existimos', missionTitle: 'Crear más posibilidades en cada mundo.', mission: ['Creemos que los jugadores de Bedrock deben tener acceso a experiencias ambiciosas y de alta calidad sin poner las ideas más interesantes detrás de un pago.', 'Nuestro trabajo abarca desde automatización industrial hasta exploración y mecánicas personalizadas, siempre con el mismo estándar: accesible al inicio, gratificante como sistema y digno de compartir.'], storyKicker: 'Nuestra historia', storyTitle: 'Construida mediante iteración.', storyLead: 'De experimentos individuales a un colectivo multidisciplinario de Bedrock.', timeline: [['2020', 'Los primeros experimentos', 'Milo504 comenzó a crear addons de Bedrock con More Armors, seguido de Tools, Weapons and More, el proyecto que con el tiempo se convertiría en UtilityCraft.'], ['2022', 'Dorios Studios toma forma', 'Milo504 y WeatherVictor fundaron Dorios Studios el 9 de septiembre, uniendo desarrollo y diseño de interfaces bajo una identidad compartida.'], ['2024', 'Un lenguaje visual más claro', 'JR.ice se unió como diseñador principal y artista de texturas. Después llegó UtilityCraft 3.0, el primer gran hito del estudio en la comunidad Bedrock.']],
      approachKicker: 'Nuestro enfoque', approachTitle: 'Principios que sobreviven al prototipo.', approachLead: 'Abre un principio para ver cómo guía el trabajo.', approaches: [['01', 'Bedrock primero', 'Diseñar para la plataforma que los jugadores realmente usan.', 'Los controles, el multijugador, el rendimiento y el ecosistema de addons Bedrock guían cada decisión desde el principio; no son una adaptación al final.'], ['02', 'Sistemas con propósito', 'Dar a cada mecánica un lugar en el progreso.', 'La automatización útil, un progreso claro y el espacio para experimentar convierten funciones aisladas en mundos que siguen siendo interesantes mañana.'], ['03', 'Moldeado por la comunidad', 'Tratar los comentarios como parte del trabajo.', 'Los jugadores y probadores ayudan a revelar qué es confuso, está desequilibrado o todavía no es divertido. Sus comentarios orientan la evolución de los addons.']],
      directoryKicker: 'Dentro del estudio', directoryTitle: 'Personas y agradecimientos.', directoryLead: 'El equipo registra quién hace el trabajo. Los créditos registran a todas las personas y herramientas que lo hacen posible.', peopleLabel: '01 / Personas', staff: 'Equipo', staffCopy: 'Conoce al equipo del estudio, sus disciplinas principales y los creadores que colaboran con nosotros.', viewStaff: 'Ver equipo', creditsLabel: '02 / Agradecimientos', credits: 'Créditos', creditsCopy: 'Colaboradores, probadores, apoyo de la comunidad y herramientas de código abierto detrás del sitio.', readCredits: 'Leer créditos', communityKicker: 'Comunidad y valores', communityTitle: 'Los comentarios son parte del proceso.', communityCopy: 'Comparte lo que funciona, reporta lo que no y ayúdanos a entender qué quieren construir después los jugadores de Bedrock. Los comentarios cuidadosos fortalecen cada lanzamiento.', joinConversation: 'Únete a la conversación', supportStudio: 'Apoya al estudio',
    },
    staff: {
      title: 'Equipo · El Estudio', description: 'Conoce al equipo y a los creadores que colaboran con Dorios Studios.', overview: 'Resumen', staff: 'Equipo', credits: 'Créditos', sectionsLabel: 'Secciones del Estudio', profileLabel: 'Ver el perfil de {name}', portraitLabel: 'Retrato de {name}', owner: 'Fundador', specialtiesLabel: 'Especialidades de {name}', kicker: 'Personas detrás del trabajo', headingBefore: 'Disciplinas diferentes. ', headingAccent: 'Un solo estudio.', lead: 'Desarrollo, interfaces, arte, animación y trabajo comunitario se reúnen aquí. Los perfiles se agrupan por la función publicada principal de cada persona.', recordLabel: 'Acerca de este registro del equipo', recordTitle: 'Acerca de este registro', recordCopy: 'Las funciones siguen los perfiles publicados actualmente por el estudio. Los enlaces personales solo se muestran cuando el estudio los ha publicado.', directoryLabel: 'Directorio del equipo de Dorios Studios', developerKicker: 'Recursos para desarrolladores', developerTitle: 'Crea con los scripts de Dorios.', developerCopy: 'Consulta la referencia de scripts, ejemplos y APIs usadas en los proyectos Bedrock del estudio.', openDocs: 'Abrir documentación de scripts', nextKicker: 'Más allá del equipo', nextTitle: 'Muchas más manos hacen posible este trabajo.', nextCopy: 'Continúa con colaboradores, probadores, agradecimientos especiales y las herramientas detrás de Dorios Studios.', exploreCredits: 'Explorar los créditos', groups: {leadership: ['Liderazgo', 'Dirección, desarrollo y la base del estudio.'], development: ['Desarrollo', 'Código, revisión de calidad e implementación de sistemas.'], 'art-design': ['Arte y Diseño', 'El lenguaje visual, el movimiento y los espacios que dan carácter a los proyectos.'], community: ['Comunidad', 'Creadores independientes que colaboran con el estudio y sus proyectos.']},
    },
    credits: {
      title: 'Créditos · El Estudio', description: 'Colaboradores, probadores, agradecimientos y herramientas detrás de Dorios Studios.', overview: 'Resumen', staff: 'Equipo', credits: 'Créditos', sectionsLabel: 'Secciones del Estudio', kicker: 'Agradecimientos', headingBefore: 'Crédito para quien ', headingAccent: 'lo merece.', lead: 'Dorios Studios crece gracias a contribuciones a proyectos, pruebas pacientes, comentarios de la comunidad y herramientas abiertas. Este registro solo incluye créditos respaldados por los archivos del estudio.', policyLabel: 'Política de créditos', policyTitle: 'Política de créditos', policyCopy: 'Un nombre faltante queda pendiente en lugar de adivinarse. Si es necesario agregar o corregir un crédito publicado, contacta al estudio por Discord.', correction: 'Solicitar una corrección', contributorsEyebrow: 'Trabajo en proyectos', contributorsTitle: 'Colaboradores', contributor: 'Colaborador acreditado · Ascendant Technology 0.8', creator: 'Creador · Better Smelters', translatorsEyebrow: 'Localización', translatorsTitle: 'Traductores', noTranslators: 'Actualmente no hay traductores individuales publicados.', translatorsCopy: 'Los créditos de localización verificados se publicarán aquí cuando el estudio los proporcione.', testersEyebrow: 'Calidad y comentarios', testersTitle: 'Probadores', testersCopy: 'Estos probadores son reconocidos por ayudar a mejorar los proyectos de Dorios Studios con pruebas y comentarios.', communityTester: 'Probador de la comunidad', thanksEyebrow: 'Permiso de recursos', thanksTitle: 'Agradecimientos especiales', thanksCopy: 'Por conceder permiso para usar los iconos de agua y Cryofluid documentados por Ascendant Technology.', originalWork: 'Ver el trabajo original', communityEyebrow: 'El círculo más amplio', communityTitle: 'Apoyo de la comunidad', communityCopy: 'A cada jugador que reporta un error, explica un sistema confuso, comparte una construcción o permanece durante una versión temprana: tus comentarios convierten experimentos en addons confiables.', joinCommunity: 'Unirse o apoyar a la comunidad', toolsEyebrow: 'Base del sitio', toolsTitle: 'Herramientas y código abierto', toolsCopy: 'Los paquetes nombrados aquí se declaran directamente en el proyecto del sitio de Dorios.', visitTool: 'Visitar {name}', nextKicker: 'El equipo actual', nextTitle: 'Conoce a las personas detrás de Dorios Studios.', nextCopy: 'Consulta las funciones publicadas de liderazgo, desarrollo, arte, diseño y comunidad.', exploreStaff: 'Explorar el equipo', toolUses: ['Framework de sitio estático y documentación', 'Capa de renderizado e interacción de componentes', 'Contenido de documentación con soporte para componentes', 'Resaltado de sintaxis legible para contenido técnico', 'Paquetes locales de las fuentes Space Grotesk y League Spartan', 'Búsqueda local en la documentación'],
    },
  },
};

function interpolate(value, values) {
  return Object.entries(values ?? {}).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, String(replacement)), value);
}

export function getPageCopy(locale, page) {
  return pageCopy[locale]?.[page] ?? pageCopy.en[page];
}

export function pageText(copy, key, values) {
  return interpolate(copy[key] ?? key, values);
}
